env_para:
  env_name: smarts
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 55 # Radius (meter) for neighborhood vehicles
  rgb_wh: 110 # Height and width (meter) of RGB image in SMARTS observation
  max_episode_steps: 1800 # 3 minutes. Maximum steps per episode.
  agent_ids: 
    - predator1
  scenarios: 
    - /home/kyber/workspaces/SMARTS/scenarios/cloverleaf
    # - /home/a84166141/workspaces/SMARTS/scenarios/cloverleaf
    # - /home/adai/workspaces/SMARTS/scenarios/cloverleaf    
    # - /src/scenarios/cloverleaf

model_para:
  # Observation and action space
  state_dim: [256, 256, 6]
  action_dim: 5
  
  # Optimizer
  initial_lr_predator: 0.001
  initial_lr_prey: 0.0005

  # PPO
  critic_loss_weight: 0.5
  entropy_loss_weight: 0.01
  entropy_loss_discount_rate: 0.995
  gamma: 0.99 # Reward discount
  clip_value: 0.2

  # Iteration size
  batch_size: 64
  max_batch: 100000000
  num_train_epochs: 5

  # Models and logs
  save_interval: 50
  mode: train # train or evaluate
  model_initial: false
  # Local
  tensorboard_path: "/home/kyber/workspaces/SMARTS/examples/gameOfTag/logs/"
  model_path: "/home/kyber/workspaces/SMARTS/examples/gameOfTag/models/"
  # model_predator: "/home/kyber/workspaces/SMARTS/examples/gameOfTag/models/predator_2021_09_10_23_17/128"
  # model_prey: "/home/kyber/workspaces/SMARTS/examples/gameOfTag/models/prey_2021_09_10_23_17/128"
  
  # tensorboard_path: "/home/adai/workspaces/SMARTS/examples/gameOfTag/logs/"
  # model_path: "/home/adai/workspaces/SMARTS/examples/gameOfTag/models/"
  # model_predator: "/home/adai/workspaces/SMARTS/examples/gameOfTag/models1/predator_2021_09_23_21_59/6464"
  # model_prey: "/home/adai/workspaces/SMARTS/examples/gameOfTag/models1/prey_2021_09_23_21_59/6464"
  
  # Docker
  # tensorboard_path: "/src/examples/gameOfTag/logs/"
  # model_path: "/src/examples/gameOfTag/models/"


# minibatch K = 3-15, 
# batch size M = 64-4096, 
# trajectory size T (horizon) = 128-2048
